# Generated by Django 4.1.7 on 2023-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='short_description',
            field=models.CharField(default='Old', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Resolved', 'Resolved')], default='Unread', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
