# Generated by Django 4.1.7 on 2023-03-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_feedback_short_description_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Added to Backlog', 'Added to Backlog'), ('Added to Roadmap', 'Added to Roadmap'), ('Resolved', 'Resolved')], default='Unread', max_length=20),
        ),
    ]
