steps:
# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
          'run',
          'deploy',
          'task-service-dev-001',
          '--platform',
          'managed',
          '--region',
          'us-west1',
          '--image',
          'us-west1-docker.pkg.dev/hl-main-dev/hl-dev-repo/hl_main_django',
          '--service-account',
          'dev-service-account@hl-main-dev.iam.gserviceaccount.com',
          '--vpc-connector',
          'projects/vpc-host-staging-yk380-hm150/locations/us-west1/connectors/dev-connector-1',
          '--set-cloudsql-instances',
          'hl-main-dev:us-west1:sql-dev-001',
          '--no-allow-unauthenticated',
    ]
  env:
    - DJANGO_ROLE=worker
    - GCP_SECRETS_NAME=squirrel-dev-002
    - GCP_PROJECT_ID=hl-main-dev
  id: 'Deploy Worker'
  entrypoint: gcloud
