steps:

# Build container image with Cloud Build from Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t',
          '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_REPO_NAME/$_GCP_IMAGE_NAME:latest',
          '--build-arg',
          'DJANGO_SETTINGS_MODULE=$_DJANGO_SETTINGS_MODULE',
          '--build-arg',
          'GCP_SECRETS_NAME=$_GCP_SECRETS_NAME',
          '--build-arg',
          'GCP_PROJECT_ID=$_GCP_PROJECT_ID',
          '.'
    ]
  id: 'Build'

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_REPO_NAME/$_GCP_IMAGE_NAME'
  ]
  id: 'Push'

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
          'run',
          'deploy',
          '$_GCP_CLOUDRUN_NAME',
          '--platform',
          'managed',
          '--region',
          '$_GCP_REGION',
          '--image',
          '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_REPO_NAME/$_GCP_IMAGE_NAME',
          '--service-account',
          '$_GCP_SERVICE_ACCOUNT',
          '--vpc-connector',
          'projects/$_VPC_HOST_PROJECT/locations/$_GCP_REGION/connectors/$_SERVERLESS_VPC_CONNECTOR',
          '--set-cloudsql-instances',
          '$_MAIN_CLOUDSQL_INSTANCE',
          '--allow-unauthenticated',
    ]
  id: 'Deploy'
  entrypoint: gcloud
images:
- '$_GCP_REGION-docker.pkg.dev/$_GCP_PROJECT_ID/$_GCP_REPO_NAME/$_GCP_IMAGE_NAME:latest'

