services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      # need to include whole app directory
      # as tailwind watches django templates
      # see frontend/tailwind.config.js
      - .:/app
    working_dir: /app/frontend
    command: sh -c "npm install && npm run watch"
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - ./gcloud:/root/.config/gcloud
      - .:/app
    working_dir: /app
    profiles:
      - 'gcloud'
    env_file:
      - .env
    # don't need to run gcloud in dev environment
    # so just run a command that does nothing and exits
    command: echo ''
  django:
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=hl_main.settings.dev
    depends_on:
      # - django-tasks
      - db
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcloud/application_default_credentials.json:ro
      - .:/app
    ports:
      - 8000:8000
    command: python manage.py runserver_plus 0.0.0.0:8000
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=hl_main.settings.dev

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  django-tasks:
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=hl_main.settings.dev
    depends_on:
      - db
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcloud/application_default_credentials.json:ro
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_ROLE=tasks
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
      - .env.dev
