apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/creator: jeff.stock@hiredlabs.org
  labels:
    cloud.googleapis.com/location: us-west1
  name: installplaywright
  namespace: '676530430552'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 444.0.0
        run.googleapis.com/cloudsql-instances: hl-main-dev:us-west1:sql-dev-001
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/vpc-host-staging-yk380-hm150/locations/us-west1/connectors/dev-connector-1
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - args:
            - 'playwright'
            - 'install'
            command:
            - '/usr/local/bin/playwright'
            env:
            - name: APPLICATION_SETTINGS
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: squirrel-dev-002
            - name: GCP_PROJECT_ID
              value: hl-main-dev
            - name: GCP_SECRETS_NAME
              value: squirrel-dev-002
            image: us-west1-docker.pkg.dev/hl-main-dev/hl-dev-repo/hl_main_django
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
          maxRetries: 3
          serviceAccountName: 676530430552-compute@developer.gserviceaccount.com
          timeoutSeconds: '600'
