# Generated by Django 4.1.7 on 2023-03-14 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Rejected", "Rejected"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        default="Submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "EMAIL"),
                            ("PHONE", "PHONE"),
                            ("IN_PERSON", "IN_PERSON"),
                            ("OTHER", "OTHER"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Interactions",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "status_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Employer Closed", "Employer Closed"),
                            ("Candidate Rejected", "Candidate Rejected"),
                            ("Cycle Complete", "Cycle Complete"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("application_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.CharField(max_length=200)),
                ("end", models.CharField(max_length=200)),
                ("result", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Phases",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "owner",
                    models.CharField(
                        choices=[
                            ("Participant", "Participant"),
                            ("Hired Labs", "Hired Labs"),
                        ],
                        default="Hired Labs",
                        max_length=20,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cold_apply.phase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Steps",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("dnc", models.BooleanField(default=False)),
                (
                    "uploaded_resume",
                    models.FileField(
                        blank=True, null=True, upload_to="./cold_apply/static/uploads/"
                    ),
                ),
                (
                    "uploaded_resume_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("veteran", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cold_apply.step",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.CreateModel(
            name="KeywordAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unigram", models.CharField(max_length=200)),
                ("bigram", models.CharField(max_length=200)),
                ("trigram", models.CharField(max_length=200)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cold_apply.job"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Keyword Analyses",
            },
        ),
    ]
