# Generated by Django 4.2.2 on 2023-08-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rates', '0001_initial'),
        ('cold_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightedbullet',
            name='bullet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet'),
        ),
        migrations.AddField(
            model_name='weightedbullet',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='weightedbullet',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position'),
        ),
        migrations.AddField(
            model_name='step',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.phase'),
        ),
        migrations.AddField(
            model_name='skillbullet',
            name='bullet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet'),
        ),
        migrations.AddField(
            model_name='skillbullet',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.skill'),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.step'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.country'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.state'),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.job'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='jobs',
            field=models.ManyToManyField(to='cold_apply.job'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='run_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.position'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletkeyword',
            name='bullet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'state', 'country')},
        ),
    ]
