# Generated by Django 4.1.7 on 2023-03-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
