# Generated by Django 4.1.7 on 2023-03-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0002_phase_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
