# Generated by Django 4.1.7 on 2023-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0002_job_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uploaded_resume_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
