# Generated by Django 4.2.2 on 2023-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Employer Closed', 'Employer Closed'), ('Admin Rejected', 'Admin Rejected'), ('Candidate Rejected', 'Candidate Rejected'), ('Cycle Complete', 'Cycle Complete')], max_length=100, null=True),
        ),
    ]
