# Generated by Django 4.1.7 on 2023-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='uploaded_resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
