# Generated by Django 4.1.7 on 2023-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0003_phase_order_step_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='owner',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Hired Labs', 'Hired Labs')], default='Hired Labs', max_length=20),
        ),
    ]
