# Generated by Django 4.2.2 on 2025-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0003_alter_job_status_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopwordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nltk english stopwords', 'NLTK English Stopwords'), ('low value', 'Low Value'), ('industry protected', 'Industry Protected')], max_length=50, unique=True)),
                ('words', models.TextField(help_text='Comma-separated list of stopwords in this category.')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
