# Generated by Django 4.2.2 on 2025-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0004_stopwordgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordanalysis',
            name='category',
            field=models.CharField(choices=[('nltk english stopwords', 'NLTK English Stopwords'), ('low value', 'Low Value'), ('industry protected', 'Industry Protected')], default='nltk english stopwords', max_length=50),
            preserve_default=False,
        ),
    ]
