# Generated by Django 4.1.7 on 2023-03-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0004_alter_participant_uploaded_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dnc',
            field=models.BooleanField(default=False),
        ),
    ]
