# Generated by Django 4.1.7 on 2023-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0005_application_dnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='dnc',
        ),
        migrations.AddField(
            model_name='participant',
            name='dnc',
            field=models.BooleanField(default=False),
        ),
    ]
