# Generated by Django 4.1.7 on 2023-03-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0005_keywordanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='bigrams',
        ),
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='trigrams',
        ),
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='unigrams',
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='bigram',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='trigram',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='unigram',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
