# Generated by Django 4.2.2 on 2025-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0005_keywordanalysis_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletkeyword',
            name='bigram',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bulletkeyword',
            name='trigram',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bulletkeyword',
            name='unigram',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='bigram',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='trigram',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='unigram',
            field=models.CharField(max_length=5000),
        ),
    ]
