# Generated by Django 4.1.7 on 2023-03-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_experience_label_alter_experience_end_date'),
        ('cold_apply', '0005_paerticipantoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.overview')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Overviews',
            },
        ),
        migrations.DeleteModel(
            name='PaerticipantOverview',
        ),
    ]
