# Generated by Django 4.1.7 on 2023-03-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0006_remove_keywordanalysis_bigrams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='updated_at',
        ),
    ]
