# Generated by Django 4.2.2 on 2025-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0006_alter_bulletkeyword_bigram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordanalysis',
            name='category',
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='bigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='trigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='unigram',
            field=models.CharField(max_length=200),
        ),
    ]
