# Generated by Django 4.1.7 on 2023-03-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_experience_label_alter_experience_end_date'),
        ('cold_apply', '0006_participantoverview_delete_paerticipantoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
            options={
                'verbose_name_plural': 'Weighted Bullets',
            },
        ),
    ]
