# Generated by Django 4.2.2 on 2025-10-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0007_remove_keywordanalysis_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletkeyword',
            name='bigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bulletkeyword',
            name='trigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bulletkeyword',
            name='unigram',
            field=models.CharField(max_length=200),
        ),
    ]
