# Generated by Django 4.1.7 on 2023-03-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_experience_label_alter_experience_end_date'),
        ('cold_apply', '0007_weightedbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletKeword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unigram', models.CharField(max_length=200)),
                ('bigram', models.CharField(max_length=200)),
                ('trigram', models.CharField(max_length=200)),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet')),
            ],
            options={
                'verbose_name_plural': 'Bullet Keywords',
            },
        ),
    ]
