# Generated by Django 4.1.7 on 2023-03-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_experience_label_alter_experience_end_date'),
        ('cold_apply', '0008_bulletkeword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulletKeword',
            new_name='BulletKeyword',
        ),
    ]
