# Generated by Django 4.2 on 2023-04-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0009_rename_bulletkeword_bulletkeyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Participants'},
        ),
    ]
