# Generated by Django 4.2.2 on 2025-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0009_alter_bulletkeyword_bigram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletkeyword',
            name='bigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bulletkeyword',
            name='trigram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='bigram',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='trigram',
            field=models.CharField(max_length=800),
        ),
    ]
