# Generated by Django 4.2 on 2023-04-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_organization_options_alter_position_options'),
        ('cold_apply', '0010_alter_participant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.education')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Education',
            },
        ),
    ]
