# Generated by Django 4.2 on 2023-04-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_concentration_name'),
        ('cold_apply', '0011_participanteducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], default='Hard', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.bullet')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.skill')),
            ],
            options={
                'verbose_name_plural': 'Skill Bullets',
            },
        ),
    ]
