# Generated by Django 4.2 on 2023-05-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0012_skill_skillbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('linkedin', models.URLField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('special_training', models.TextField(blank=True, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('job_links', models.TextField(blank=True, null=True)),
                ('work_preferences', models.TextField(blank=True, null=True)),
                ('service_branch', models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('Marines', 'Marines'), ('Coast Guard', 'Coast Guard'), ('Space Force', 'Space Force'), ('Not a Veteran', 'Not a Veteran')], default='Not a Veteran', max_length=200, null=True)),
                ('military_specialiaty', models.CharField(max_length=200, null=True)),
                ('years_of_service', models.IntegerField(null=True)),
                ('rank_at_separation', models.CharField(max_length=200, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.location')),
            ],
        ),
    ]
