# Generated by Django 4.2 on 2023-05-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_remove_skill_code_skill_base'),
        ('cold_apply', '0014_state_alter_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.country'),
        ),
    ]
