# Generated by Django 4.2 on 2023-05-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0015_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
