# Generated by Django 4.2.1 on 2023-05-31 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0017_remove_participantexperience_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightedbullet',
            options={'ordering': ['-weight'], 'verbose_name_plural': 'Weighted Bullets'},
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.location'),
        ),
    ]
