# Generated by Django 4.2.1 on 2023-05-31 10:22

from django.db import migrations


def update_names(apps, schema_editor):
    for participant in apps.get_model("cold_apply", "Participant").objects.all():
        try:
            first_name, last_name = participant.name.split(" ")
            participant.first_name = first_name
            participant.last_name = last_name
            participant.save()
        except ValueError:
            pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "cold_apply",
            "0018_alter_weightedbullet_options_participant_first_name_and_more",
        ),
    ]

    operations = [migrations.RunPython(update_names)]
