# Generated by Django 4.2.1 on 2023-06-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_remove_skill_code_skill_base'),
        ('cold_apply', '0019_auto_20230531_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'state', 'country')},
        ),
    ]
