# Generated by Django 4.2.2 on 2023-06-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0021_job_location_job_location_detail_job_posted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='scraped_id',
            new_name='source_id',
        ),
    ]
