# Generated by Django 4.2.2 on 2023-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0022_rename_scraped_id_job_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
