# Generated by Django 4.2.2 on 2023-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0023_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_agent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
