# Generated by Django 4.2.2 on 2023-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0025_alter_job_application_link_alter_job_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
