# Generated by Django 4.2.2 on 2023-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0026_job_company_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
