# Generated by Django 4.2.2 on 2023-06-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0027_job_auto_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='source_link',
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.location'),
        ),
    ]
