# Generated by Django 4.2.2 on 2023-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0028_remove_job_source_link_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_agent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
