# Generated by Django 4.2.2 on 2023-06-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cold_apply', '0029_alter_job_application_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_apply.applicant'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Employer Closed', 'Employer Closed'), ('Admin Rejected', 'Admin Rejected'), ('Candidate Rejected', 'Candidate Rejected'), ('Cycle Complete', 'Cycle Complete')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField()),
                ('keywords_csv', models.TextField()),
                ('date_posted', models.CharField(choices=[('today', 'Today'), ('3days', 'Three Days'), ('week', 'Week'), ('month', 'Month'), ('all', 'All')], max_length=20)),
                ('distance_miles', models.IntegerField()),
                ('result_count', models.IntegerField()),
                ('duplicate_count', models.IntegerField()),
                ('duplicates_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs', models.ManyToManyField(to='cold_apply.job')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
                ('searching_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
