# Generated by Django 4.2.2 on 2023-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0030_participant_applicant_alter_job_status_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='duplicates_json',
            field=models.JSONField(null=True),
        ),
    ]
