# Generated by Django 4.2.2 on 2023-06-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0031_alter_jobsearch_duplicates_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='searching_user',
            new_name='run_by',
        ),
    ]
