# Generated by Django 4.2.2 on 2023-06-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0032_rename_searching_user_jobsearch_run_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='date_posted',
            field=models.CharField(blank=True, choices=[('today', 'Today'), ('3days', 'Three Days'), ('week', 'Week'), ('month', 'Month'), ('all', 'All')], max_length=20),
        ),
    ]
