# Generated by Django 4.2.2 on 2023-06-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0033_alter_jobsearch_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
