# Generated by Django 4.2.2 on 2023-06-14 15:48

from django.db import migrations


def update_names(apps, schema_editor):
    for applicant in apps.get_model("cold_apply", "Applicant").objects.all():
        try:
            first_name, last_name = applicant.name.split(" ")
            applicant.first_name = first_name
            applicant.last_name = last_name
            applicant.save()
        except ValueError:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("cold_apply", "0034_applicant_first_name_applicant_last_name"),
    ]

    operations = [
        migrations.RunPython(update_names),
    ]
