# Generated by Django 4.2.2 on 2023-06-14 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0035_auto_20230614_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-first_name', '-last_name']},
        ),
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
