# Generated by Django 4.2.2 on 2023-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0036_alter_applicant_options_applicant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=50),
        ),
    ]
