# Generated by Django 4.2.2 on 2023-06-14 16:15

from django.db import migrations

from cold_apply.models import Participant


def update_applicants(apps, schema_editor):
    applicant_model = apps.get_model("cold_apply", "Applicant")
    participant_model = apps.get_model("cold_apply", "Participant")
    for applicant in applicant_model.objects.all():
        participant = participant_model.objects.filter(email=applicant.email).first()
        if (
            participant
            and not participant_model.objects.filter(applicant=applicant).exists()
        ):
            participant.applicant = applicant
            participant.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cold_apply", "0037_applicant_status"),
    ]

    operations = [
        migrations.RunPython(update_applicants),
    ]
