# Generated by Django 4.2.2 on 2023-08-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0040_remove_applicant_status_applicant_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dnc',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='uploaded_resume',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='uploaded_resume_title',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='veteran',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
