# Generated by Django 4.2.2 on 2023-08-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cold_apply', '0042_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
