# Generated by Django 4.2.2 on 2023-08-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('hdi', models.CharField(choices=[('VERY HIGH', 'VERY HIGH'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default=None, max_length=10, null=True)),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default=None, max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')])),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('employer_country', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='employer_country', to='rates.country')),
            ],
            options={
                'verbose_name_plural': 'Rate Requests',
                'ordering': ['-time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('median_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('lowest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('rate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.raterequest')),
            ],
        ),
        migrations.AddField(
            model_name='raterequest',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.skill'),
        ),
        migrations.AddField(
            model_name='raterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raterequest',
            name='worker_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_country', to='rates.country'),
        ),
    ]
