# Generated by Django 4.1.5 on 2023-01-27 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('employer_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_country', to='rates.country')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('median_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('lowest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('rate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.raterequest')),
            ],
        ),
        migrations.AddField(
            model_name='raterequest',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.skill'),
        ),
        migrations.AddField(
            model_name='raterequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raterequest',
            name='worker_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_country', to='rates.country'),
        ),
    ]
