# Generated by Django 4.1.5 on 2023-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
