# Generated by Django 4.1.5 on 2023-01-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_remove_country_code_country_rank_country_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='hdi',
            field=models.CharField(choices=[('VERY HIGH', 'VERY HIGH'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default=None, max_length=10, null=True),
        ),
    ]
