# Generated by Django 4.1.5 on 2023-01-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_country_hdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='zone',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default=None, max_length=1, null=True),
        ),
    ]
