# Generated by Django 4.1.6 on 2023-04-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_skill_code_alter_country_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='raterequest',
            options={'ordering': ['-time_stamp'], 'verbose_name_plural': 'Rate Requests'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='rateresponse',
            name='time_stamp',
        ),
        migrations.AlterField(
            model_name='raterequest',
            name='employer_country',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='employer_country', to='rates.country'),
        ),
        migrations.AlterField(
            model_name='raterequest',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')]),
        ),
    ]
