# Generated by Django 4.1.6 on 2023-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_alter_raterequest_employer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='code',
        ),
        migrations.AddField(
            model_name='skill',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
