# Generated by Django 4.2.2 on 2023-08-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VeteranProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_branch', models.CharField(choices=[('ARMY', 'Army'), ('NAVY', 'Navy'), ('AIR_FORCE', 'Air Force'), ('MARINES', 'Marines'), ('COAST_GUARD', 'Coast Guard'), ('SPACE_FORCE', 'Space Force')], default='Not a Veteran', max_length=200, null=True)),
                ('military_specialiaty', models.CharField(max_length=200, null=True)),
                ('years_of_service', models.IntegerField(null=True)),
                ('rank_at_separation', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('is_veteran', models.BooleanField(null=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('resume', models.FileField(null=True, upload_to='uploads/')),
                ('special_training', models.TextField(blank=True, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('job_links', models.TextField(blank=True, null=True)),
                ('work_preferences', models.TextField(blank=True, null=True)),
                ('onboarding_step', models.CharField(choices=[('PROFILE', 'Profile'), ('VETERAN_PROFILE', 'Veteran Status'), ('SERVICE_PACKAGE', 'Service Package'), ('UPLOAD_RESUME', 'Upload Resume'), ('COMPLETE', 'Complete')], default='PROFILE', max_length=20)),
                ('dnc', models.BooleanField(default=False)),
                ('service_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.servicepackage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
