# Generated by Django 4.2.2 on 2023-08-16 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_veteran',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='job_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.CharField(choices=[('VERIFY_EMAIL', 'Verify Email'), ('PROFILE', 'Profile'), ('VETERAN_PROFILE', 'Veteran PROFILE'), ('SERVICE_PACKAGE', 'Service Package'), ('UPLOAD_RESUME', 'Upload Resume'), ('COMPLETE', 'Complete')], default='PROFILE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_training',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VeteranProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_branch', models.CharField(choices=[('ARMY', 'Army'), ('NAVY', 'Navy'), ('AIR_FORCE', 'Air Force'), ('MARINES', 'Marines'), ('COAST_GUARD', 'Coast Guard'), ('SPACE_FORCE', 'Space Force')], default='Not a Veteran', max_length=200, null=True)),
                ('military_specialiaty', models.CharField(max_length=200, null=True)),
                ('years_of_service', models.IntegerField(null=True)),
                ('rank_at_separation', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='service_package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userprofile.servicepackage'),
            preserve_default=False,
        ),
    ]
