# Generated by Django 4.2.2 on 2023-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='veteran_verified',
            field=models.BooleanField(default=False),
        ),
    ]
