# Generated by Django 4.2.2 on 2023-08-19 12:03

from django.db import migrations


def create_site_enty(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site, _ = Site.objects.get_or_create(id=1)
    site.name = "hiredlabs.org"
    site.domain = "hiredlabs.org"
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0002_profile_veteran_verified"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = []
