# Generated by Django 4.2.2 on 2023-08-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_servicepackage_profile_created_at_profile_dnc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_veteran',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onboarding_step',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('VETERAN_PROFILE', 'Veteran PROFILE'), ('SERVICE_PACKAGE', 'Service Package'), ('UPLOAD_RESUME', 'Upload Resume'), ('COMPLETE', 'Complete')], default='PROFILE', max_length=20),
        ),
    ]
