# Generated by Django 4.2.2 on 2023-08-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_is_veteran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.servicepackage'),
        ),
    ]
