# Generated by Django 4.2.2 on 2023-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_service_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onboarding_step',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('VETERAN_PROFILE', 'Veteran Status'), ('SERVICE_PACKAGE', 'Service Package'), ('UPLOAD_RESUME', 'Upload Resume'), ('COMPLETE', 'Complete')], default='PROFILE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
