# Generated by Django 4.2.2 on 2023-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='None Entered', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_documents',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
