# Generated by Django 4.2.2 on 2023-10-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_profile_address_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service_documents',
        ),
        migrations.AddField(
            model_name='veteranprofile',
            name='service_doc',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
