# Generated by Django 4.2.2 on 2023-11-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='None Entered'),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='None Entered', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='None Entered', max_length=200),
        ),
    ]
