# Generated by Django 4.2.2 on 2023-12-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_comment_comment_comment_email_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='military_specialiaty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank_at_separation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_branch',
            field=models.CharField(choices=[('ARMY', 'US Army'), ('NAVY', 'US Navy'), ('AIR_FORCE', 'US Air Force'), ('MARINE CORPS', 'US Marine Corps'), ('COAST_GUARD', 'US Coast Guard'), ('SPACE_FORCE', 'Space Force')], default='Not a Veteran', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_doc',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_service',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_veteran',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_package',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.servicepackage'),
        ),
    ]
