# Generated by Django 4.2.2 on 2023-12-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_remove_profile_birthdate_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='None Entered', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_doc',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
