# Generated by Django 4.2.2 on 2023-12-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_profile_linkedin_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_step',
        ),
    ]
