# Generated by Django 4.2.2 on 2023-08-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cold_apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abbr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('lang_type', models.CharField(choices=[('Human', 'Human'), ('Computer', 'Computer'), ('Framework', 'Framework'), ('Ability', 'Ability'), ('Technology', 'Technology'), ('Skill', 'Skill')], max_length=20)),
                ('level', models.CharField(choices=[('Native', 'Native'), ('Fluent', 'Fluent'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('Beginner', 'Beginner'), ('Novice', 'Novice')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(blank=True, choices=[('Work', 'Work'), ('Edu', 'Edu'), ('Activity', 'Activity')], default='Work', max_length=20)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('website', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Positions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('auto_generated', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
                ('title', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Coursework Completed'), ('in_progress', 'In Progress')], default='completed', max_length=50)),
                ('concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.concentration')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.degree')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CertProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('variety', models.CharField(choices=[('Certification', 'Certification'), ('Project', 'Project'), ('Activity', 'Activity'), ('Award', 'Award')], max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('Work', 'Work'), ('Summary', 'Summary')], max_length=20)),
                ('auto_generated', models.BooleanField(default=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experience')),
                ('skills', models.ManyToManyField(blank=True, through='cold_apply.SkillBullet', to='cold_apply.skill')),
            ],
        ),
    ]
