# Generated by Django 4.1.1 on 2022-11-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abbr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('lang_type', models.CharField(choices=[('Human', 'Human'), ('Computer', 'Computer'), ('Framework', 'Framework'), ('Ability', 'Ability'), ('Technology', 'Technology'), ('Skill', 'Skill')], max_length=20)),
                ('level', models.CharField(choices=[('Native', 'Native'), ('Fluent', 'Fluent'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('Beginner', 'Beginner'), ('Novice', 'Novice')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(choices=[('Program Manager', 'Program Manager'), ('Sales Engineer', 'Sales Engineer'), ('NLP Developer', 'NLP Developer')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(choices=[('Work', 'Work'), ('Leadership', 'Leadership')], max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.concentration')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.degree')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CertProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('variety', models.CharField(choices=[('Certification', 'Certification'), ('Project', 'Project'), ('Activity', 'Activity')], max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('Work', 'Work'), ('Summary', 'Summary')], max_length=20)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experience')),
            ],
        ),
    ]
