# Generated by Django 4.1.1 on 2022-11-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chronological_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('Work', 'Work'), ('Edu', 'Edu'), ('Activity', 'Activity')], default=None, max_length=20, null=True),
        ),
    ]
