# Generated by Django 4.1.7 on 2023-03-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='whose',
        ),
    ]
