# Generated by Django 4.1.7 on 2023-03-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_organization_chronological_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='title',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.position'),
        ),
    ]
