# Generated by Django 4.1.7 on 2023-03-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_position_whose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='label',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
