# Generated by Django 4.1.7 on 2023-03-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_overview_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='chronological_order',
        ),
    ]
