# Generated by Django 4.2 on 2023-04-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_organization_options_alter_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title'], 'verbose_name_plural': 'Positions'},
        ),
    ]
