# Generated by Django 4.2 on 2023-04-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_organization_options_alter_position_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='abbr',
            field=models.CharField(max_length=20),
        ),
    ]
