# Generated by Django 4.2 on 2023-04-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_degree_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
