# Generated by Django 4.2 on 2023-05-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0016_alter_applicant_location'),
        ('resume', '0007_alter_concentration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='experience',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='overview',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
    ]
