# Generated by Django 4.2 on 2023-05-24 19:48

from django.db import migrations


def update_participant_ids(apps, schema_editor):
    part_exp_model = apps.get_model("cold_apply", "ParticipantExperience")
    exp_model = apps.get_model("resume", "Experience")

    for exp in exp_model.objects.all():
        try:
            exp.participant_id = part_exp_model.objects.get(
                experience_id=exp.id
            ).participant_id
            exp.save()
        except:
            exp.delete()

    part_edu_model = apps.get_model("cold_apply", "ParticipantEducation")
    edu_model = apps.get_model("resume", "Education")

    for edu in edu_model.objects.all():
        try:
            edu.participant_id = part_edu_model.objects.get(
                education_id=exp.id
            ).participant_id
            edu.save()
        except:
            edu.delete()

    part_over_model = apps.get_model("cold_apply", "ParticipantOverview")
    over_model = apps.get_model("resume", "Overview")

    for over in over_model.objects.all():
        try:
            over.participant_id = part_over_model.objects.get(
                overview_id=exp.id
            ).participant_id
            over.save()
        except:
            over.delete()



class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_education_participant_experience_participant_and_more"),
    ]

    operations = [migrations.RunPython(update_participant_ids)]
