# Generated by Django 4.2 on 2023-05-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0017_remove_participantexperience_experience_and_more'),
        ('resume', '0009_auto_20230524_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
    ]
