# Generated by Django 4.2.1 on 2023-05-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0018_alter_weightedbullet_options_participant_first_name_and_more'),
        ('resume', '0010_alter_education_participant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='bullet',
            name='skills',
            field=models.ManyToManyField(blank=True, through='cold_apply.SkillBullet', to='cold_apply.skill'),
        ),
        migrations.AlterField(
            model_name='certprojectactivity',
            name='variety',
            field=models.CharField(choices=[('Certification', 'Certification'), ('Project', 'Project'), ('Activity', 'Activity'), ('Award', 'Award')], max_length=20),
        ),
    ]
