# Generated by Django 4.2.1 on 2023-05-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_apply', '0019_auto_20230531_1122'),
        ('resume', '0011_alter_experience_options_bullet_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certprojectactivity',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_apply.participant'),
        ),
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('completed', 'Coursework Completed'), ('in_progress', 'In Progress')], default='completed', max_length=50),
        ),
    ]
