# Generated by Django 4.2.2 on 2023-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_certprojectactivity_participant_education_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
