# Generated by Django 4.2.2 on 2023-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Edu', 'Edu'), ('Activity', 'Activity')], default='Work', max_length=20),
        ),
    ]
