# Generated by Django 4.2.2 on 2023-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_organization_name_alter_organization_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
