# Generated by Django 4.2.2 on 2023-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_bullet_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
