# Generated by Django 4.2.2 on 2023-07-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_id', models.CharField(blank=True, max_length=36)),
                ('target_path', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(null=True)),
                ('result', models.TextField()),
            ],
        ),
    ]
